### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by 726f62696e** [hvdwolf/pyExifToolGUI#13]
because of that last [commit](https://github.com/hvdwolf/pyExifToolGUI/commit/e4e55a934f8febc02c0b2104f97f920aa347df68)
  File "/usr/lib/python2.7/site-packages/scripts/petgfilehandling.py", line 147, in write_default_lensdb
    userpath = os.environ('HOME')
AttributeError: _Environ instance has no __call__ method
It should have been `userpath = os.environ['HOME']`

**Comment by hvdwolf** [comment]
You are right. I changed it in a local copy and then typed it directly into
the website git making the typo, instead of commiting the local change.

2015-06-28 8:43 GMT+02:00 robin <notifications@github.com>:
