### ISSUE TITLE
No actions performed by program

### ISSUE THREAD

**Issue by m-prol** [hvdwolf/pyExifToolGUI#14]
I encountered the following issues after normal installation according to INSTALLATION.txt and installing python-pyside.
My System: Kubuntu 15.04, KDE 4.14.8
1. Slight unclarity in installation hints:
   INSTALLATION.txt is slightly misleading, when pointing out to a dependency to pyside and another dependency to python-pyside. It is probably the same package and not two different ones.
2. Problems with video files:
   pyexiftoolgui only offers to open image files, not video files. Opening an video file by selecting _._ in the file browser allows opening of such a video file. There only the makernotes are displayed. including options to change date, etc. Changing the date results in no changes at all. I wonder where the makernote comes from, as nothing is displayed in the exif-section, where the information comes from, as far as I know.
3. Problem with changing image files:
   Even loading an image file and trying to change it's creation date, etc. results in nothing. Just nothing happenes. Also changing file time-stamp does not work.
4. Unclarity of the GUI:
   It is unclear if you can apply changes while viewing data in the "view" section, via right mouse button, where the according options appear - but with no result as explained in 3. Does one have to change to edit-section, where just some forms are displayed with none available metadata?
   In the edit-section-Exif, there is no data preset for the actual date of the image.
   So probably if one only want to shift the date, one would have to edit this in the view-section.
5. Refresh when loading an image:
   When the view is set to e.g. makernotes and you load an image, the data displayed is only refreshed when clicking somewhere else and back to makernotes. Thus one could think, there is no metadata within the loaded image.

Btw. is the makernote section a combination of the information of the other sections? I never heard of it.

**Comment by hvdwolf** [comment]
Hi,

2. It is basically a image metadata editor. exiftool as such has support for videos but not extensively either. When opening files you have the option to set the filter to image files, image/video/pdf and other files that exiftool knows, and all files. So there is a possibility toopen video files directly from pyExiftToolGUI.

3. This is very hard to reproduce. I used my tool 2 days ago to change a big set of images and Idonot recognise your issues, which makes it hard for me to "fix" them.

4. View is only view: That's what it is saying. The Edit tab is for editing. Personally I think that is obvious.
Generally speaking you might be right about unclarity in the GUI. I'm not an ergonomic expert and only try to make the program in a way I think is as user-friendly as possible but I might be wrong or simply not reaching my goal.

5. I'm not extremely satisfied with the refreshing myself, but I have not spend much time the last year on the application as it did what I expected from it. I just started programming again.

Makernotes have nothing to do with the "maker of the photo", but with the maker of the equipment. It can contain camera data and lens data but also serial numbers, etc, depending on complexity of the camera (compact, mirror-less version with lenses, DSLRs,etc) and depending on the brand (company) of the camera and/or lens. It is more or less what the firmware of the camera is telling about itself.
