### ISSUE TITLE
Feature request: copy/paste KML/GPX

### ISSUE THREAD

**Issue by trond7** [hvdwolf/pyExifToolGUI#15]
It would be a nice feature to support pasting KML and/or GPX and parse it to location metadata fill out the GPS form.

The filling out the geo metadata would be mush faster using service as e.g
http://mygeoposition.com/.
1. Use the service above to find a location.
2. Go to the KML og GPX tab and copy the complete location object.
3. Paste it to pyExifToolGUI and it will fill out the form.

One cut and paste operation instead of several.

**Comment by hvdwolf** [comment]
Hi,

I see what you mean and it could be nice indeed. I will have a look at it, but that's currently the only thing I can say about it.

Harry
