### ISSUE TITLE
Feature request - Keep last dir accessed as default for loading images

### ISSUE THREAD

**Issue by pmi123** [hvdwolf/pyExifToolGUI#16]
Great program and very useful. It would be much faster to access images as one is scanning them if the program would remember the last directory that was accessed for loading the images. Or, add a preferences menu item to set a default working directory.

I am scanning hundreds of photos, and occasionally need to add some EXIF metadata to one of them. Every time I need to load an image, I have to start at root (/) and traverse the directory tree to get to the scanned image on my external usb drive. The "Look in:" drop down does not remember the last location I used to load the images. I am using version 0.5.

Thanks!

Mark

**Comment by hvdwolf** [comment]
Hmmm. This is a bug. It worked in previous versions but you are right. Strange that I did not notice it myself. I'll check it.

**Comment by pmi123** [comment]
OK, thanks!

I thought it was a little strange that it did not work as expected. ;)

Mark

**Comment by hvdwolf** [comment]
On second thought: It has never been in there and it isn't a bug either. The program always moves to the default user pictures folder depending on the OS. You can overrule that by specifiying another folder in the preferences. I have as low prio on my own wishlist to add a setting to this folder preference to "always open last used location", but Im not that far yet.

**Comment by pmi123** [comment]
The default for load images is /home/mark/Pictures on my Ubuntu 14.0.4 LTS
laptop, so it is getting that value from somewhere.

I couldn't find a preferences menu entry.

The preferences tab only has the path to the exiftool, and default values
for Creator/artist/photographer and Copyrights/Rights.

Is there a text file somewhere that has the default path that I can change?
Is there a way to paste the correct path from the clipboard?

Mark
