### ISSUE TITLE
Install issues 

### ISSUE THREAD

**Issue by renarios** [hvdwolf/pyExifToolGUI#18]
Hi!
I just tried to install pyExifToolGUI on my Fedora 23 system using:

**./install_remove.py install**
This gives the following output:

_You have chosen to install pyExiftoolGUI on your system_
# 

_usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]_
-   or: setup.py --help [cmd1 cmd2 ...]*
-   or: setup.py --help-commands*
-   or: setup.py cmd --help*

_error: option --install-layout not recognized_
# 

If you didn't see errors on your screen, pyExifToolGui has been installed.
In case of errors contact me.
You might also see a lot of "kbuildsycoca4" messages.
This is the cache being rebuilt and your application
being added to menus and so on.*

When I run *_python setup.py install --install-lib=/usr/share/pyexiftoolgui --install-scripts=/usr/bin *_ (without _--install-layout=deb_), it installs even with startmenu icon, but it doesn't execute.

When I issue **pyexiftoolgui** from the command line, I recieve the following:
*Real folder where this launcher was started from: /usr/bin
We are not running from our source folder. Are we running from /usr/bin?
Yes we are running from /usr/bin 

usr_share_path /usr/share/pyexiftoolgui/scripts/pyexiftoolgui.py

starting pyexiftoolgui using: /usr/bin/env python /usr/share/pyexiftoolgui/scripts/pyexiftoolgui.py

Program start: We are on python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
Traceback (most recent call last):
  File "/usr/share/pyexiftoolgui/scripts/pyexiftoolgui.py", line 56, in <module>
    import petgfunctions
  File "/usr/share/pyexiftoolgui/scripts/petgfunctions.py", line 35, in <module>
    from ui_create_args import Ui_Dialog_create_args
ImportError: cannot import name Ui_Dialog_create_args*

Can U help me out?

**Comment by hvdwolf** [comment]
I assume it is the same error as reported by Zverik (https://github.com/hvdwolf/pyExifToolGUI/issues/11). He could work around.
I'm sorry to say but I more or less stopped developments due to all kind of reasons. Maybe I will try to release a "bug fix" this spring compensating for the new developments changes in several systems and distributions.
