### ISSUE TITLE
Install issue on Mac OSX

### ISSUE THREAD

**Issue by Fremax** [hvdwolf/pyExifToolGUI#19]
Dear,
I installed exiftool 10.10 and it works in terminal.
Now I installed pyExifToolGUI by dragging your .app bundle into my application folder, but on startup it says exif tool is missing or incorrectly setup in preferences. 
A windows open to locate exiftool, but I couldn't locate it.
I can't figure out how to fix this.
Any help?
Thank you

**Comment by Dekoninck** [comment]
Hi,

I experienced exactly the same on OSX 10.11.3

Getz

**Comment by hvdwolf** [comment]
I will work on it. in the mean time check issue https://github.com/hvdwolf/pyExifToolGUI/issues/17
It is about exactly the same issue and contains some hints.

**Comment by Dekoninck** [comment]
I followed the issue #17 and indeed I got it to work. Startup is also after a few times firing the program. 
Thanks for helping out and working on it.

**Comment by schroef** [comment]
i have this same issue on OSX 10.11.6 i also have th exiftool 10.56 already installed. Still see that error message
