### ISSUE TITLE
Won't load in Kubuntu 15.10

### ISSUE THREAD

**Issue by daititt** [hvdwolf/pyExifToolGUI#20]
Seems to install fine.  When I try to run it, I get result below.  Any help?

~$ pyexiftoolgui
Real folder where this launcher was started from: /usr/bin
We are not running from our source folder. Are we running from /usr/bin?
Yes we are running from /usr/bin 

usr_share_path /usr/share/pyexiftoolgui/scripts/pyexiftoolgui.py

starting pyexiftoolgui using: /usr/bin/env python /usr/share/pyexiftoolgui/scripts/pyexiftoolgui.py

Program start: We are on python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]
Traceback (most recent call last):
  File "/usr/share/pyexiftoolgui/scripts/pyexiftoolgui.py", line 56, in <module>
    import petgfunctions
  File "/usr/share/pyexiftoolgui/scripts/petgfunctions.py", line 33, in <module>
    from ui_create_args import Ui_Dialog_create_args
ImportError: cannot import name Ui_Dialog_create_args

**Comment by smillertr8** [comment]
I think I fixed this by running ./pycomp.sh before running install.

Then mkdir "~/.pyexiftoolgui" before running the app.  
But don't create an empty config.xml file - it doesn't like that!
