### ISSUE TITLE
Yosemite PyExifToolGui won't Save

### ISSUE THREAD

**Issue by TeamRainless** [hvdwolf/pyExifToolGUI#22]
This is the most frustrating program that I've tried to run in a very long time. I'm using Yosemite. No problem getting it to run. It simply won't actually work.  Won't actually save the EXIF info.
1. I have the app installed in applications.
2. I have Pyside installed
3. I have python27-pyside installed
4. I have the tools for QT installed (QT 5.6 requires a 14GB install... at THAT point I'm better off just editing the EXIF info in lightroom or photoshop.) But the tools are installed and hopefully that's all I need.

But I load data from an image and click "Save to Image" once I've edited the Data I want... It simply doesn't save anything.  Nothing at all.

What the hell am I missing?

**Comment by ryodels** [comment]
I'm using MacOS Sierra and have the same issue, but I just installed the app in applications. I already had exiftool installed for some time (insider usr/local/bin/ ... Already solved that problem).

Playing with the app I realized that when I use the menu to change a date /time it works. But when I try the same from the "edit" tab it doesn't ... I see it is writing the file but the file remains the same ... I can even see that some temporal file is created while it is writing the file.
