### ISSUE TITLE
pyExiftoolGui Does Not Always Launch on MAC OS X Yosemite

### ISSUE THREAD

**Issue by rizvisk** [hvdwolf/pyExifToolGUI#27]
I am running the following.

OS X Yosemite 10.10.5
Exiftool 10.23
pyExiftoolGui 0.5

I have updated the config file to point to the location of Exiftool on my machine. When I click the icon for pyExifToolGui in Application folder or using Launchpad, I see the icon come on to the Dock but then it disappears without launching. The app does not provide any error messages either. After clicking the app icon 10 or 20 times, it does launch the app and seems to work OK.

I have deleted and reinstalled the pyexiftoolgui but that has not helped. By the way, this is the first time I have installed pyexiftoolgui.

I am wondering if others have experienced this issue and if there is a fix for it. I have reviewed the issues and do not see anything similar. Thanks.

**Comment by alexpopov** [comment]
I am having similar issues. It fully launched and worked once. If I launch it from the command-line I get the following:

```

**Comment by gitguys** [comment]
Does pyExifToolGUI work with macOS Sierra?

**Comment by gitguys** [comment]
Does pyExifToolGUI work with macOS Sierra?

**Comment by cosmolux** [comment]
Yes, pyExifToolGUI works with macOS Sierra, but because it always instantly crashed from double-clicking the icon I had to launch it from the command line:
`/Applications/pyexiftoolgui.app/Contents/MacOS/pyexiftoolgui`
