### ISSUE TITLE
Ubuntu 16.04 commant not found

### ISSUE THREAD

**Issue by ebuy-4-you** [hvdwolf/pyExifToolGUI#30]
All files are in place and all Dependencies installed

Release 16.04.1 LTS (Xenial Xerus) 64-bit
Kernel Linux 4.4.0-57-generic x86_64
MATE 1.12.1
AMD E2-3800 APU with Radeon(TM) HD Graphics × 4

/pyExifToolGUI-0.5/pyexiftoolgui.pro: line 1: SOURCES: command not found
: No such file or directory5/pyexiftoolgui.pro: line 2: scripts/IFfunctions.py
: No such file or directory5/pyexiftoolgui.pro: line 3: scripts/about.py
: No such file or directory5/pyexiftoolgui.pro: line 4: scripts/license.py
: No such file or directory5/pyexiftoolgui.pro: line 5: scripts/image_info.py
: No such file or directory5/pyexiftoolgui.pro: line 6: scripts/programinfo.py
: No such file or directory5/pyexiftoolgui.pro: line 7: ui/ui_About.py
: No such file or directory5/pyexiftoolgui.pro: line 8: ui/ui_license.py
: No such file or directory5/pyexiftoolgui.pro: line 9: ui/ui_MainWindow.py
/home/xxxx/pyExifToolGUI-0.5/pyexiftoolgui.pro: line 10: $'\r': command not foun

/home/ebuy/pyExifToolGUI-0.5/pyexiftoolgui.pro: line 11: TRANSLATIONS: command not found
: No such file or directory5/pyexiftoolgui.pro: line 12: i18n/en_US.ts
: No such file or directory5/pyexiftoolgui.pro: line 13: i18n/fr_FR.ts
: No such file or directory5/pyexiftoolgui.pro: line 14: i18n/de_DE.ts
: No such file or directory5/pyexiftoolgui.pro: line 15: i18n/es_ES.ts
: No such file or directory5/pyexiftoolgui.pro: line 16: i18n/nl_NL.ts
/home/xxxxx/pyExifToolGUI-0.5/pyexiftoolgui.pro: line 17: $'\r': command not found

sudo ./setup.py install
sudo: ./setup.py: command not found

**Comment by hvdwolf** [comment]
Did you read the online manual? https://hvdwolf.github.io/pyExifToolGUI/manual/pyexiftoolgui.html#InstallLinux

You used the old <0.32 version install.
You should do "sudo ./install_remove.py install"

pyExifToolGUI will be installed and you should have an icon in your menu under the Graphics sub menu or in your Dash (Ubuntu).
You can then also start it from the terminal with "pyexiftoolgui &"

The .pro file is a QT project "building" file and has nothing to do with starting the application.

**Comment by ebuy-4-you** [comment]
you are right that did the trick
