### ISSUE TITLE
Can't open image if path contain non-ASCII character

### ISSUE THREAD

**Issue by TomaszGasior** [hvdwolf/pyExifToolGUI#31]
Application can't open image if its path contain non-ASCII characters, for example:
/home/tomasz/Obrazy/Zdj**ę**cia/W**ę**gry/W**ę**gry 1.jpg

Error output in console:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scripts/pyexiftoolgui.py", line 518, in imageinfo
    petgfunctions.imageinfo(self,qApp)
  File "/usr/lib/python2.7/site-packages/scripts/petgfunctions.py", line 390, in imageinfo
    args = shlex.split(command_line)
  File "/usr/lib/python2.7/shlex.py", line 275, in split
    lex = shlex(s, posix=posix)
  File "/usr/lib/python2.7/shlex.py", line 25, in __init__
    instream = StringIO(instream)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0119' in position 39: ordinal not in range(128)

**Comment by AngelArnal** [comment]
Same here. The images directory in Spanish is "Imágenes" and it's not accessible. I don't get any error message, the program just doesn't allow to choose that directory. Folders with non-ASCII appear greyed-out (see image). Network units just don't appear.
![captura de pantalla de 2017-10-07 14 07 53](https://user-images.githubusercontent.com/23248254/31307665-4430f22c-ab69-11e7-8ab1-d98a2feb4fec.png)

**Comment by TomaszGasior** [comment]
Any errors in terminal output?

**Comment by AngelArnal** [comment]
Nope, it seems normal
