### ISSUE TITLE
Installer is not using /usr/local and requires root-privileges to install

### ISSUE THREAD

**Issue by zybork** [hvdwolf/pyExifToolGUI#34]
I am sorry, but it is completely out of the question to run an installer that requires root-privileges and tries to install its files in /usr instead of e.g. /usr/local (or /opt or something else). So I either have to go through every single line of every script in question, or simply chose not to try pyExifToolGUI.

I know I might come across as a bit nitty-picky here, but it is important. Your tool looks promising, and I'd really love to try it out.

**Comment by hvdwolf** [comment]
I completely agree with you on the /usr versus /usr/local part.

But the fact that you need root privileges is also necessary when installing it in /usr/local. 
What's more: Every package manager on linux needs root privileges to install packages unless you install it inside your own user space. 
No matter whether you use apt-get, yum, rpm, or slackware tools, you need root-privileges.
