### ISSUE TITLE
Publish Debian packages

### ISSUE THREAD

**Issue by darkdragon-001** [hvdwolf/pyExifToolGUI#36]
It seems that Debian package creation works already. Please upload these binaries to releases as well!

Also it would be really appreciated if you could also create a script to build them automatically!

**Comment by 243750496** [comment]
sudo apt-get install libimage-exiftool-perl
then delete zip suffix ,and type sudo dpkg -i pyexiftoolgui*.deb, 
tested on ubuntu 17.10 and 17.04
if you have problem with the package and need to remove it just uninstall from synaptic
BTW:i am not developer and not good at pacage the code,if you can do it better please replace it . 
[pyexiftoolgui_0.40_all.deb.zip](https://github.com/hvdwolf/pyExifToolGUI/files/1587030/pyexiftoolgui_0.40_all.deb.zip)

**Comment by darkdragon-001** [comment]
@hvdwolf It would be nice if you could publish binary _deb_ packages for your [releases](https://github.com/hvdwolf/pyExifToolGUI/releases).
