### ISSUE TITLE
Pose Pitch and Roll Degrees

### ISSUE THREAD

**Issue by Serendigity** [hvdwolf/pyExifToolGUI#42]
When using  360 camera such as Ricoh Theta and holding the camera on a pole at an oblique angle the pitch and roll will be out of standard horizontal/vertical. There are many ways to correct the image for viewing and some do not change the metadata so the image will then be inconsistent with some key embedded metadata for heading, pitch and roll.  Facebook uses specific XMP data when displaying a 360 image:
Pose Heading Degrees
Pose Pitch Degrees
Pose Roll Degrees

Your graphical front end panel to alter GPano information has the ability to add values for the fields:
Initial View Heading Degrees
Initial View Pitch Degrees
Initial View Roll Degrees
Initial Horizontal FOV Degrees

Facebook seems to ignore all these values, and instead uses the camera initially recorded data.

![gpano](https://user-images.githubusercontent.com/45026713/51446550-8dd49d80-1d63-11e9-8486-c31a89e801ec.jpg)
![fields](https://user-images.githubusercontent.com/45026713/51446551-8dd49d80-1d63-11e9-897c-8bfb07e8b6c9.jpg)

Can I request that you please either:
a)  allow any data field to be altered in the View Data pane.  The field titles and values are there, just they cannot be changed; or
b) include the Pose Heading Degrees, Pose Pitch Degrees and Pose Roll Degrees fields which are the ones Facebook uses.  Thank you.

**Comment by hvdwolf** [comment]
You also have the tab "Your Commands".
See the online manual: https://hvdwolf.github.io/pyExifToolGUI/manual/pyexiftoolgui.html#YourCommands

Please try with -GPSPitch=1 -GPSRoll=-19.2 (or whatever values)
I do not know how to add the heading.
For reference please also read https://www.sno.phy.queensu.ca/~phil/exiftool/geotag.html
