### ISSUE TITLE
Photos aren't considered loaded, error : "No photos loaded yet"

### ISSUE THREAD

**Issue by CalTheme** [hvdwolf/pyExifToolGUI#44]
Hello,

First of all thank you for this Graphic interface for exiftool, it may save us a lot of time.
Here is the problem : I'm on Windows 10 an I followed the instalation instruction, no problem at this point.
I'm on pyexiftoolgui 0.5 and i'm loading images, they appear in the viewer location, but display not a single data on "view data".
So I tried to "export metadata" to verify if it may work, but it instead show at the end of the configuraton a popup named "No photos loaded yet" : "You did not load or select any  photos yet" even if I did.

Your interface may have issues to remember or accept the fact that I did loaded an image (.jpg format)
Here is an image to proove it :
![image](https://user-images.githubusercontent.com/33475535/57426483-0efc6580-726b-11e9-9c3c-e1af20440b35.png)

Thanks you for you time.

**Comment by hvdwolf** [comment]
You should select the file name, not the thumbnail.
I know that is not user-friendly, but that is how it is.

Note that I discontinued the application as pySide is hard to maintain and package for the several Operating systems. So the mentioned behavior will not change anymore.

I'm currently building on jExifToolGUI: the exact same app but than in java. It is so easy to package that for the several OSes and the GUI is straightforward.
