### ISSUE TITLE
 pyExifToolGUI  not working with Xubuntu 20.04

### ISSUE THREAD

**Issue by thomas0469** [hvdwolf/pyExifToolGUI#47]
After upgrading from 19.10 to 20.04 I noticed pyExifToolGUI does not start any more. It seems to me that the reason is that python-pyside is no longer available for 20.04. Is there any fix for that?

**Comment by hvdwolf** [comment]
Hi.
Sorry, but like mentioned on the website: I do not support this package anymore. Especially because pyside is getting harder and harder to support. You can still install, but not any longer via Xubuntu itself.
Please try https://pypi.org/project/PySide/
